### ISSUE TITLE
Manejo de cancelar compra

### ISSUE THREAD

**Issue by manuelabarca** [rgcl/webpay-nodejs#14]
Hola una consulta que no he podido dar con ella, como manejo el control de los siguientes errores

Si el usuario cierra el portal de pago, como le digo a la peticion, cortate, porque como que queda en cola la peticion soap.

Si el banco tuvo un problema y cerro el portal, como detecto eso ?

Si el usuario le da anular, vi que habia una forma en este caso, pero no lo entendi del todo el authorizacion code, entre otros

Alguna ayuda, actualmente lo adapte con socket.io para abrir un webview en una aplicacion hibrida creada con ionic 3 y tambien la adapte de la misma forma para angular. Saludos

**Comment by morello-cl** [comment]
Transbank te notifica. Y tienes tú página donde tiene que llegar la última redirección. En caso que nada de eso ocurra, tienes que verificar en el portal en que estado quedo la transacción, y anularla si es necesario, eso en un caso extremo.





---- On Tue, 12 Mar 2019 10:32:10 -0300 Manuel Labarca <notifications@github.com> wrote ----



Hola una consulta que no he podido dar con ella, como manejo el control de los siguientes errores

Si el usuario cierra el portal de pago, como le digo a la peticion, cortate, porque como que queda en cola la peticion soap.

Si el banco tuvo un problema y cerro el portal, como detecto eso ?

Si el usuario le da anular, vi que habia una forma en este caso, pero no lo entendi del todo el authorizacion code, entre otros

Alguna ayuda, actualmente lo adapte con socket.io para abrir un webview en una aplicacion hibrida creada con ionic 3 y tambien la adapte de la misma forma para angular. Saludos

**Comment by manuelabarca** [comment]
Gracias tratare de orientarme con tu respuesta, si alguien tiene más info, Se agradece. Saludos.

**Comment by rgcl** [comment]
Espero que lo hayas resuelto. Si la duda continúa, por favor reabre el hilo. Saludos.
