### ISSUE TITLE
Error: Could not find openssl on your system on this path: openssl 

### ISSUE THREAD

**Issue by MarioHazard** [rgcl/webpay-nodejs#18]
Hola, estoy trabajando con fastify en vez de express. En local, initTransaction() me genera el token y la url, pero en producción (Google Cloud App Engine) me arroja el siguiente error:

Error: Could not find openssl on your system on this path: openssl      at /usr/src/app/node_modules/pem/lib/openssl.js:237:23      at F (/usr/src/app/node_modules/which/which.js:68:16)      at E (/usr/src/app/node_modules/which/which.js:80:29)      at /usr/src/app/node_modules/which/which.js:89:16      at /usr/src/app/node_modules/isexe/index.js:42:5      at /usr/src/app/node_modules/isexe/mode.js:8:5      at FSReqWrap.oncomplete (fs.js:154:21)
2019-11-03 06:30:04 default[20191030t042847]  "POST /webpay" 502

la función es la siguiente:

const pay = async (req, res) => {
    let buyOrden = Date.now();
    //transactions[buyOrden] = { amount: amount};
    let url = 'xxxxxx';

    await wp.initTransaction({
      buyOrder: buyOrden,
      sessionId: req.body.sessionId,
      returnURL: url + '/verify',
      finalURL: url + '/voucher',
      amount: 10000
    }).then((data) => {
        return res.send(data.url + '?token_ws=' + data.token);
    }).catch(onError(res));
  };

**Comment by rgcl** [comment]
Hola, ese await mezclado con promesas se me hace raro. En cualquier caso, una nueva versión v1.4.0 salió hace poco que corrige varias cosas. Por favor, prueba con la nueva versión y reabre el hilo si el error persiste.

**Comment by lreyessandoval** [comment]
Hola @MarioHazard  me apareció algo similar, instale el openssl y además agregue el path a las variables de entorno de windows.  Con eso ya no hubo mas problema....  Acá un link donde esta el detalle de como hacerlo.....

https://medium.com/swlh/installing-openssl-on-windows-10-and-updating-path-80992e26f6a1
