### ISSUE TITLE
webpaykey

### ISSUE THREAD

**Issue by MauricioDonoso** [rgcl/webpay-nodejs#19]
Hola, 
me entrega el sgte error y no me deja avanzar, ya cree la llave publica y privada con el codigo de comercio que me entrego transbank
initTransaction:error! { Error: soap:Server: 
    at finish (/**/node_modules/soap/lib/wsdl.js:1488:21)

**Comment by rgcl** [comment]
Hola, por favor, prueba con la nueva versión v1.4.0. Si el problema persiste reabre éste issue.
