### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by Gonzalo9823** [rgcl/webpay-nodejs#2]
Hola! Al momento de hacer una transacción me esta dando este error, que puede ser?

Este es mi codigo:

```
apiRoutes.post('/webpay/new', (req, ress) => {

    let buyOrden = Date.now();
    let amount = 1000;
    let url = 'https://www.******.cl';

    wp.initTransaction({
        buyOrder: buyOrden,
        sessionId: req.sessionId,
        returnURL: url + '/verificar',
        finalURL: url + '/comprobante',
        amount: amount
    }).then((data) => {
        ress.json({
            status: 1,
            url: data.url + '?token_ws=' + data.token
        })
    });
})
```

**Comment by rgcl** [comment]
Hola, por favor, agrega un .catch(..) luego del .then(..) con un
console.log(error), luego copia y pega aquí lo que arroje la consola para
poder ver qué puede ser.

Ejemplo:
...

.then((data) => {
    ress.json({
        status: 1,
        url: data.url + '?token_ws=' + data.token
    })
}).catch(console.log);

**Comment by Gonzalo9823** [comment]
Hola, ya lo logre hacer funcionar, muchas gracias igual por tu ayuda

**Comment by manuelabarca** [comment]
> Hola, ya lo logre hacer funcionar, muchas gracias igual por tu ayuda

hola me sale un error al iniciar la transacción
"initTransaction:error! { Error: soap:Server: For input string: """
