### ISSUE TITLE
Los ejemplos estan funcionando?

### ISSUE THREAD

**Issue by Danzed** [rgcl/webpay-nodejs#7]
No he realizado nada, solo queria probar la libreria. Corrí el testNormal.js y lanza "initTransaction: result doesn't have a valid signature!".

Se cae en esta linea: 
`let res = sig.checkSignature(xml);`

**Comment by rgcl** [comment]
Hola, disculpa la demora.
Efectivamente *no* estaban funcionando. Esto se debe a que Transbank silenciosamente(?) cambió el certificado .pem y por tanto las firmas no eran validas. Eso se corrigió con la nueva versión.

En cualquier caso eso solo era para el ejemplo, en producción hubiera funcionado bien (con las credenciales correctas).
