### ISSUE TITLE
Como generar certificado webpay

### ISSUE THREAD

**Issue by manuelabarca** [rgcl/webpay-nodejs#8]
Hola buenos días como genero el certificado webpay, debido a que según TBK tengo que generar solo dos certificados con el codigo de comercio, uno publico y uno privado, pero según tu libreria tengo que tener un webpay cert, no comprendo ese punto y lo otro puedo probarlo en localhost ? o tengo que tener una ip fija. 

Saludos, estoy intentando hacer que webpay haga la transacción pero quiero manejar las vistas en Angular

Muchas gracias de ante mano.

**Comment by nicolaslopezj** [comment]
Tienes que completar el documento y enviarlo a soporte@transbank.cl


[Evidencia.docx](https://github.com/rgcl/webpay-nodejs/files/2498140/Evidencia.docx)

**Comment by tebantebanteban** [comment]
En este link hay documentación nueva sobre la integración https://www.transbankdevelopers.cl/documentacion/como_empezar 

pero yo la encuentro un poco mas engorrosa que el documento antiguo 

[Referencia API SOAP Webpay General.pdf](https://github.com/rgcl/webpay-nodejs/files/2498144/Referencia.API.SOAP.Webpay.General.pdf)


Paso 1: instalar la librería
Paso 2: Bajar los certificados y tener a mano los datos de prueba para la integración.

Generalmente transbank hace cambiar los certificados una vez al lado por lo que yo prefiero tenerlos de manera física e importarlos de esta manera:   

`
```
config.ambTBK = 'pro';
config.TBK_WP = {
	'cer' : {
			'CCTBK' : '597020000541',
			'TBKcert' : fs.readFileSync('TBK_KEYS/tbk.pem'),
			'publicKey' : fs.readFileSync('TBK_KEYS/597020000541.crt'),
			'privateKey' : fs.readFileSync('TBK_KEYS/597020000541.key')
	},
	'pro' : {
			'CCTBK' : 'XXXXXXX',
			'TBKcert' : fs.readFileSync('TBK_KEYS/serverTBK.crt'),
			'publicKey' : fs.readFileSync('TBK_KEYS/XXXXXXX.crt'),
			'privateKey' : fs.readFileSync('TBK_KEYS/XXXXXXX.key')
	}
	
}
````


De lo anterior, puedes rescatar que el código de comercio de integración para Webpay Plus es **597020000541**. dentro de los archivos a descargar vienen el TBKcert, publicKet y privateKey con los que puedes realizar todas tus pruebas de integración.


Una vez que tu ciclo funcione excelente, debes enviar a transbank el documento que @nicolaslopezj   te adjuntó. Haciendo todas y cada una de las pruebas que ahí señalan.

Una vez que transbank la revisé y te asigne un código de comercio, tendrás que generar tus certificados autofirmados según instrucciones del pdf que te adjunté o incluso ellos mismos en el correo que te envían te pagan el extracto sobre como generarlos.

Esos certificados serán el XXXXXXX.crt y XXXXXXX.key.  Cuando el proceso esté completo, transbank te enviará el serverTBK.crt que es válido tanto para Webpay plus como para webpay oneclick.

Después de eso puedes cambiar tu ambiente de transbank a 'pro' y listo!

**Comment by rgcl** [comment]
Gracias por responder c:

Como no hay más actividad, lo cierro.
